version: '3'

services:
  nginxServer:
    image: nginx:stable
    container_name: nginxServer
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxServer:/etc/nginx/conf.d

  dockerGen:
    image: jwilder/docker-gen:0.7
    container_name: dockerGen
    restart: always
    depends_on:
      - nginxServer
    volumes:
      - nginxServer:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    command:
      -notify-sighup nginxServer -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

volumes:
  nginxServer:

networks:
  default:
    external:
      name: gateway
